default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--profile=black"
          - "--line-length=120"

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      args:
        - "--line-length=120"

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: misc
      additional_dependencies:
        - flake8-builtins==1.5.3
        - flake8-bugbear==21.11.29
        - flake8-comprehensions==3.7.0
        - flake8-use-fstring==1.3
      args:
        - "--max-line-length=120"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        args:
          - "--strict"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
